class wishes:
    print("hello")
    def msg(self):
        print("siva")
        print("good morning")
    print("how are you")
w1=wishes()
w1.msg()
w1.msg()
w1.msg()
w1.msg()
w2=wishes()
w2.msg()
w2.msg()
w3=wishes()
w3.msg()
w3.msg()
print("bye")
